"""
NE301 配置生成工具测试

测试 ne301_config.py 模块的核心功能
"""
import pytest
from pathlib import Path
from app.core.ne301_config import (
    generate_ne301_json_config,
    extract_tflite_quantization_params,
    NE301Toolchain,
    get_ne301_toolchain,
    NE301ConfigManager,
)


class TestExtractVersionVar:
    """测试 _extract_version_var() 版本变量解析"""

    def test_extract_with_colon_assign(self, tmp_path: Path):
        """测试使用 := 语法的变量提取（标准语法）"""
        toolchain = get_ne301_toolchain(tmp_path)
        content = "VERSION_MAJOR := 2\nVERSION_MINOR := 0\n"

        major = toolchain._extract_version_var(content, "VERSION_MAJOR", 3)
        minor = toolchain._extract_version_var(content, "VERSION_MINOR", 1)

        assert major == 2
        assert minor == 0

    def test_extract_missing_var(self, tmp_path: Path):
        """测试缺失变量的情况（应返回默认值）"""
        toolchain = get_ne301_toolchain(tmp_path)
        content = "VERSION_MAJOR := 2\n"

        major = toolchain._extract_version_var(content, "VERSION_MAJOR", 3)
        minor = toolchain._extract_version_var(content, "VERSION_MINOR", 0)
        patch = toolchain._extract_version_var(content, "VERSION_PATCH", 1)

        # 存在的变量返回实际值
        assert major == 2
        # 缺失的变量返回默认值
        assert minor == 0
        assert patch == 1

    def test_extract_with_comments(self, tmp_path: Path):
        """测试包含注释的变量提取"""
        toolchain = get_ne301_toolchain(tmp_path)
        content = (
            "# Version configuration\n"
            "VERSION_MAJOR := 2  # Major version\n"
            "VERSION_MINOR := 0  # Minor version\n"
        )

        major = toolchain._extract_version_var(content, "VERSION_MAJOR", 3)
        minor = toolchain._extract_version_var(content, "VERSION_MINOR", 1)

        # 应该正确处理注释
        assert major == 2
        assert minor == 0


class TestModelVersionOverride:
    """测试 MODEL_VERSION_OVERRIDE 优先级"""

    def test_override_with_env_var(self, tmp_path: Path, monkeypatch):
        """测试通过环境变量覆盖版本号

        注意：当前实现不支持环境变量覆盖，此测试作为未来扩展预留
        """
        # 创建 version.mk 文件
        version_mk = tmp_path / "version.mk"
        version_mk.write_text(
            "VERSION_MAJOR := 2\n"
            "VERSION_MINOR := 0\n"
            "VERSION_PATCH := 1\n"
            "VERSION_BUILD := 123\n"
        )

        # 设置环境变量（如果未来支持）
        # monkeypatch.setenv("MODEL_VERSION_OVERRIDE", "3.1.0.456")

        toolchain = get_ne301_toolchain(tmp_path)
        version = toolchain.get_model_version()

        # 当前实现：应该读取 version.mk 中的版本号
        # 未来扩展：环境变量优先级更高
        assert version.to_tuple() == (2, 0, 1, 123)


class TestVersionParsingIntegration:
    """测试版本号解析集成功能"""

    def test_parse_real_version_mk(self, tmp_path: Path):
        """集成测试：解析真实的 version.mk 文件"""
        # 模拟真实的 version.mk 文件
        version_mk = tmp_path / "version.mk"
        version_mk.write_text(
            "# NE301 SDK Version Configuration\n"
            "# Auto-generated by build system\n"
            "\n"
            "VERSION_MAJOR := 3\n"
            "VERSION_MINOR := 0\n"
            "VERSION_PATCH := 0\n"
            "VERSION_BUILD := 1\n"
        )

        toolchain = get_ne301_toolchain(tmp_path)
        version = toolchain.get_model_version()

        # 验证完整解析流程
        assert version.major == 3
        assert version.minor == 0
        assert version.patch == 0
        assert version.build == 1
        assert str(version) == "3.0.0.1"

    def test_toolchain_caching(self, tmp_path: Path):
        """测试工具链缓存机制"""
        # 第一次获取
        toolchain1 = get_ne301_toolchain(tmp_path)

        # 第二次获取（应该返回缓存的实例）
        toolchain2 = get_ne301_toolchain(tmp_path)

        # 验证是同一个实例
        assert toolchain1 is toolchain2

    def test_different_project_paths(self, tmp_path: Path):
        """测试不同项目路径的工具链实例"""
        # 创建两个不同的项目路径
        project1 = tmp_path / "project1"
        project2 = tmp_path / "project2"
        project1.mkdir()
        project2.mkdir()

        # 为项目 1 创建 version.mk
        version_mk1 = project1 / "version.mk"
        version_mk1.write_text(
            "VERSION_MAJOR := 2\n"
            "VERSION_MINOR := 0\n"
            "VERSION_PATCH := 0\n"
            "VERSION_BUILD := 100\n"
        )

        # 为项目 2 创建 version.mk
        version_mk2 = project2 / "version.mk"
        version_mk2.write_text(
            "VERSION_MAJOR := 3\n"
            "VERSION_MINOR := 1\n"
            "VERSION_PATCH := 0\n"
            "VERSION_BUILD := 200\n"
        )

        # 获取两个项目的工具链
        toolchain1 = get_ne301_toolchain(project1)
        toolchain2 = get_ne301_toolchain(project2)

        # 验证是不同的实例
        assert toolchain1 is not toolchain2

        # 验证版本号不同
        version1 = toolchain1.get_model_version()
        version2 = toolchain2.get_model_version()

        assert version1.to_tuple() == (2, 0, 0, 100)
        assert version2.to_tuple() == (3, 1, 0, 200)

